package CsBaseLanguage.tests.EditorAndStructure;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;

@MPSLaunch
public class ClassDeclaration_WithGenericsWhere_ClassType_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(ClassDeclaration_WithGenericsWhere_ClassType_Test.class, "${project_home}", "r:fcdf8a98-8638-4be9-822b-7c6b6a82fdf7(CsBaseLanguage.tests.EditorAndStructure@tests)", false);

  public ClassDeclaration_WithGenericsWhere_ClassType_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_ClassDeclaration_WithGenericsWhere_ClassType() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("2009189856894835680", "2009189856894835685");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      typeString("where");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      typeString("class");


    }
  }
}
