package CsBaseLanguage.tests.EditorAndStructure;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

@MPSLaunch
public class EnumDeclaration_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(EnumDeclaration_Test.class, "${project_home}", "r:fcdf8a98-8638-4be9-822b-7c6b6a82fdf7(CsBaseLanguage.tests.EditorAndStructure@tests)", false);

  public EnumDeclaration_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_EnumDeclaration() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("627877194145017634", "627877194145017617");
      typeString("enum");
      typeString("Commands");

      pressKeys(ListSequence.fromListAndArray(new ArrayList<String>(), " TAB"));

      invokeAction("jetbrains.mps.ide.editor.actions.Insert_Action");
      typeString("Start");
      pressKeys(ListSequence.fromListAndArray(new ArrayList<String>(), " ENTER"));

      invokeAction("jetbrains.mps.ide.editor.actions.Insert_Action");
      typeString("Stop");
    }
  }
}
