package CsBaseLanguage.tests.EditorAndStructure;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;

@MPSLaunch
public class StructDeclaration_WithGenericsWhere_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(StructDeclaration_WithGenericsWhere_Test.class, "${project_home}", "r:fcdf8a98-8638-4be9-822b-7c6b6a82fdf7(CsBaseLanguage.tests.EditorAndStructure@tests)", false);

  public StructDeclaration_WithGenericsWhere_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_StructDeclaration_WithGenericsWhere() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("627877194145446474", "627877194145446538");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      typeString("where");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      invokeAction("jetbrains.mps.ide.editor.actions.MoveRight_Action");
      typeString("class");


    }
  }
}
