package CalculatorDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Calculator = 0;
  public static final int Input = 1;
  public static final int InputReference = 2;
  public static final int Output = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L);
    builder.put(0x49159080d531d84fL, Calculator);
    builder.put(0x49159080d531d850L, Input);
    builder.put(0x49159080d531d854L, InputReference);
    builder.put(0x49159080d531d851L, Output);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
