package CalculatorDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInput = createDescriptorForInput();
  /*package*/ final ConceptDescriptor myConceptInputReference = createDescriptorForInputReference();
  /*package*/ final ConceptDescriptor myConceptOutput = createDescriptorForOutput();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xd74e25c94d9143b6L, 0xbad7d18af7bf6674L, "CsBaseLanguage");
    deps.aggregatedLanguage(0xd74e25c94d9143b6L, 0xbad7d18af7bf6674L, "CsBaseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInput, myConceptInputReference, myConceptOutput);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.Input:
        return myConceptInput;
      case LanguageConceptSwitch.InputReference:
        return myConceptInputReference;
      case LanguageConceptSwitch.Output:
        return myConceptOutput;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CalculatorDSL", "Calculator", 0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d84fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6ef7c9ce-c679-41d0-bf83-7ad98b8f5e77(CalculatorDSL.structure)/5266274222286690383");
    b.version(2);
    b.aggregate("input", 0x49159080d531d859L).target(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d850L).optional(true).ordered(true).multiple(true).origin("5266274222286690393").done();
    b.aggregate("output", 0x49159080d531d85bL).target(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d851L).optional(true).ordered(true).multiple(true).origin("5266274222286690395").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CalculatorDSL", "Input", 0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d850L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6ef7c9ce-c679-41d0-bf83-7ad98b8f5e77(CalculatorDSL.structure)/5266274222286690384");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CalculatorDSL", "InputReference", 0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d854L);
    b.class_(false, false, false);
    b.super_("CsBaseLanguage.structure.Expression", 0xd74e25c94d9143b6L, 0xbad7d18af7bf6674L, 0x5ef9203ea4c50c1cL);
    b.origin("r:6ef7c9ce-c679-41d0-bf83-7ad98b8f5e77(CalculatorDSL.structure)/5266274222286690388");
    b.version(2);
    b.associate("input", 0x49159080d531d85eL).target(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d850L).optional(false).origin("5266274222286690398").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CalculatorDSL", "Output", 0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d851L);
    b.class_(false, false, false);
    b.origin("r:6ef7c9ce-c679-41d0-bf83-7ad98b8f5e77(CalculatorDSL.structure)/5266274222286690385");
    b.version(2);
    b.aggregate("expression", 0x49159080d531d852L).target(0xd74e25c94d9143b6L, 0xbad7d18af7bf6674L, 0x5ef9203ea4c50c1cL).optional(false).ordered(true).multiple(false).origin("5266274222286690386").done();
    return b.create();
  }
}
