package CalculatorDSL.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Calculator_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Input_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new InputReference_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Output_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new InputReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d84fL), MetaIdFactory.conceptId(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d850L), MetaIdFactory.conceptId(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d854L), MetaIdFactory.conceptId(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d851L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d854L)).seal();
}
