package CsBaseLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Class_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ClassMember_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ClassType_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new CodeBlock_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new IntType_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new MethodDefinition_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new PrivateVisibilityModifier_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new ProtectedVisibilityModifier_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new PublicVisibilityModifier_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new Statement_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new StaticModifier_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ClassType_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa448b56cL), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa449646aL), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44afc63L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44a6d7eL), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44a6ca9L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44a6ca4L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44964b4L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44964bbL), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44964a5L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44a6d82L), MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44b75f6L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x250303846d664bd0L, 0xbe085e945e7502b5L, 0x7b67658aa44afc63L)).seal();
}
