package CalculatorDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class InputReference_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.input$9Y92), LINKS.value$rdy5), PROPS.value$paYa));
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink input$9Y92 = MetaAdapterFactory.getReferenceLink(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d854L, 0x49159080d531d85eL, "input");
    /*package*/ static final SContainmentLink value$rdy5 = MetaAdapterFactory.getContainmentLink(0xc78e965abaf24f43L, 0x8d2083e096ac81b5L, 0x49159080d531d850L, 0x49159080d53c5ce4L, "value");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$paYa = MetaAdapterFactory.getProperty(0xd74e25c94d9143b6L, 0xbad7d18af7bf6674L, 0x5ef9203ea4ca99eeL, 0x2b6e5dd872e3d465L, "value");
  }
}
